$(document).ready(function(){
  $('.container1').click(function(){
    $(this).toggleClass('slide');
  })

 $('.container2').click(function(){
    $(this).toggleClass('slide');
  })

  $('.container3').click(function(){
    $(this).toggleClass('slide');
  })

   $('.container4').click(function(){
    $(this).toggleClass('slide');
  })

    $('.container5').click(function(){
    $(this).toggleClass('slide');
  })

     $('.container6').click(function(){
    $(this).toggleClass('slide');
  })

      $('.container7').click(function(){
    $(this).toggleClass('slide');
  })

       $('.container8').click(function(){
    $(this).toggleClass('slide');
  })
       $('.container9').click(function(){
    $(this).toggleClass('slide');
  })
       $('.container10').click(function(){
    $(this).toggleClass('slide');
  })
       $('.container11').click(function(){
    $(this).toggleClass('slide');
  })
       $('.container12').click(function(){
    $(this).toggleClass('slide');
  })

       $('.container13').click(function(){
    $(this).toggleClass('slide');
  })

       $('.container14').click(function(){
    $(this).toggleClass('slide');
  })

       $('.container15').click(function(){
    $(this).toggleClass('slide');
  })

       $('.container16').click(function(){
    $(this).toggleClass('slide');
  })
        $('.container17').click(function(){
    $(this).toggleClass('slide');
  })
         $('.container18').click(function(){
    $(this).toggleClass('slide');
  })
          $('.container19').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container20').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container21').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container22').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container23').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container24').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container25').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container26').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container27').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container28').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container29').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container30').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container31').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container32').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container33').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container34').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container35').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container36').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container37').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container38').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container39').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container40').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container41').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container42').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container43').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container44').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container45').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container46').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container47').click(function(){
    $(this).toggleClass('slide');
  })
           $('.container48').click(function(){
    $(this).toggleClass('slide');
  })
             $('.container49').click(function(){
    $(this).toggleClass('slide');
  })
               $('.container50').click(function(){
    $(this).toggleClass('slide');
  })
 
})
